def launch_with(config_filename)
  if ENV['tag']
    test_options = "-r ./config/#{config_filename} --order random --tag #{ENV['tag']}"
  else
    test_options = "-r ./config/#{config_filename} --order random"
  end
  system("parallel_rspec --test-options '#{test_options}' spec")
end

def run_sequentially(config_filename)
  system("rspec --test-options '-r ./config/#{config_filename}' spec")
end

=begin
desc 'Run tests locally'
task :local, :browser do |t, args|
  ENV['browser'] = args[:browser]
  launch_with('config_local.rb')
end


desc 'Run tests in Sauce Labs'
task :cloud do
  launch_with('config_cloud.rb')
end
=end

namespace :cloud do
  BROWSERS_CLOUD = ['firefox', 'chrome', 'internet_explorer']
  BROWSERS_CLOUD.each do |browser|
    desc "Run tests in Sauce Labs on #{browser.capitalize}"
    task browser.to_sym, :version, :os do |t, args|
      ENV['browser'] = browser
      ENV['browser_version'] = args[:version]
      ENV['operating_system'] = args[:os]
      launch_with('config_cloud.rb')
    end
  end
end

namespace :local do
  BROWSERS_LOCAL = [ 'chrome', 'firefox', 'internet_explorer']
  BROWSERS_LOCAL.each do |browser|
    desc "Run tests locally on #{browser.capitalize}"
    task browser.to_sym do
      ENV['browser'] = browser
      launch_with('config_local.rb')
    end
  end
end